name: Release Build and Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.target.os_name }}
    runs-on: ${{ matrix.target.os_runner }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - os_name: Linux
            os_runner: ubuntu-latest
            asset_filename: projectson-linux-amd64
            base_app_name: projectson
            fyne_os_target: linux
          - os_name: Windows
            os_runner: windows-latest
            asset_filename: projectson-windows-amd64.exe
            base_app_name: projectson
            fyne_os_target: windows
          - os_name: macOS
            os_runner: macos-latest
            asset_filename: projectson-macos-amd64.app.zip
            base_app_name: projectson
            fyne_os_target: darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Install Linux Fyne dependencies
        if: matrix.target.os_name == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev \
                                  libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev \
                                  libxi-dev libxxf86vm-dev \
                                  xorg-dev gcc pkg-config libgtk-3-dev

      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Check for icon.png
        id: check_icon
        shell: bash
        run: |
          if [[ -f "icon.png" ]]; then
            echo "icon_exists=true" >> $GITHUB_OUTPUT
          else
            echo "icon_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build for Linux (using go build directly)
        if: matrix.target.os_name == 'Linux'
        shell: bash
        run: |
          APP_ID_VALUE="looqey.projectson.go"
          # Compile directly with go build
          go build -o ${{ matrix.target.asset_filename }} -ldflags="-X 'main.AppID=$APP_ID_VALUE'" .
          # Make it executable
          chmod +x ${{ matrix.target.asset_filename }}

      - name: Build for Windows and macOS (using Fyne package)
        if: matrix.target.os_name != 'Linux'
        shell: bash
        run: |
          APP_ID_VALUE="looqey.projectson.go"
          if [[ "${{ steps.check_icon.outputs.icon_exists }}" == "true" ]]; then
            fyne package -os ${{ matrix.target.fyne_os_target }} -icon icon.png --app-id $APP_ID_VALUE -name ${{ matrix.target.base_app_name }} -release
          else
            fyne package -os ${{ matrix.target.fyne_os_target }} --app-id $APP_ID_VALUE -name ${{ matrix.target.base_app_name }} -release
          fi

      - name: Prepare macOS artifact (zip .app bundle)
        if: matrix.target.os_name == 'macOS'
        shell: bash
        run: |
          zip -r ${{ matrix.target.asset_filename }} ${{ matrix.target.base_app_name }}.app

      # Update path based on the target OS
      - name: Upload Linux artifact
        if: matrix.target.os_name == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.asset_filename }}
          path: ${{ matrix.target.asset_filename }}
          if-no-files-found: error

      - name: Upload Windows artifact
        if: matrix.target.os_name == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.asset_filename }}
          path: ${{ matrix.target.base_app_name }}.exe
          if-no-files-found: error

      - name: Upload macOS artifact
        if: matrix.target.os_name == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.asset_filename }}
          path: ${{ matrix.target.asset_filename }}
          if-no-files-found: error

  create_release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Rename Windows artifact
        run: |
          if [ -f "./artifacts/projectson-windows-amd64.exe/projectson.exe" ]; then
            mkdir -p ./release-files
            cp ./artifacts/projectson-windows-amd64.exe/projectson.exe ./release-files/projectson-windows-amd64.exe
          fi
          
          if [ -f "./artifacts/projectson-linux-amd64/projectson-linux-amd64" ]; then
            mkdir -p ./release-files
            cp ./artifacts/projectson-linux-amd64/projectson-linux-amd64 ./release-files/projectson-linux-amd64
          fi
          
          if [ -f "./artifacts/projectson-macos-amd64.app.zip/projectson-macos-amd64.app.zip" ]; then
            mkdir -p ./release-files
            cp ./artifacts/projectson-macos-amd64.app.zip/projectson-macos-amd64.app.zip ./release-files/projectson-macos-amd64.app.zip
          fi
          
          echo "Files prepared for release:"
          ls -la ./release-files || echo "No files found in release-files directory"

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Автоматический релиз версии ${{ github.ref_name }}.

            **Собранные файлы:**
            - `projectson-linux-amd64`: Исполняемый файл для Linux (amd64)
            - `projectson-windows-amd64.exe`: Исполняемый файл для Windows (amd64)
            - `projectson-macos-amd64.app.zip`: Приложение для macOS (amd64, .app в zip-архиве)
          draft: false
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
          files: |
            ./release-files/*